/*
**	Command & Conquer Generals Zero Hour(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

////////////////////////////////////////////////////////////////////////////////
//																																						//
//  (c) 2001-2003 Electronic Arts Inc.																				//
//																																						//
////////////////////////////////////////////////////////////////////////////////


#include "PreRTS.h"	// This must go first in EVERY cpp file int the GameEngine

#include "Common/CRC.h"
#include "GameNetwork/Transport.h"
#include "GameNetwork/NetworkInterface.h"

#ifdef _INTERNAL
// for occasional debugging...
//#pragma optimize("", off)
//#pragma MESSAGE("************************************** WARNING, optimization disabled for debugging purposes")
#endif

//--------------------------------------------------------------------------
// Packet-level encryption is an XOR operation, for speed reasons.  To get
// the max throughput, we only XOR whole 4-byte words, so the last bytes
// can be non-XOR'd.

// This assumes the buf is a multiple of 4 bytes.  Extra is not encrypted.
static inline void encryptBuf( unsigned char *buf, Int len )
{
	UnsignedInt mask = 0x0000Fade;

	UnsignedInt *uintPtr = (UnsignedInt *) (buf);

	for (int i=0 ; i<len/4 ; i++) {
		*uintPtr = (*uintPtr) ^ mask;
		*uintPtr = htonl(*uintPtr);
		uintPtr++;
		mask += 0x00000321; // just for fun
	}
}

// This assumes the buf is a multiple of 4 bytes.  Extra is not encrypted.
static inline void decryptBuf( unsigned char *buf, Int len )
{
	UnsignedInt mask = 0x0000Fade;

	UnsignedInt *uintPtr = (UnsignedInt *) (buf);

	for (int i=0 ; i<len/4 ; i++) {
		*uintPtr = htonl(*uintPtr);
		*uintPtr = (*uintPtr) ^ mask;
		uintPtr++;
		mask += 0x00000321; // just for fun
	}
}

//--------------------------------------------------------------------------
// Packet authentication.  The XOR transform above is a fixed, public
// obfuscation and the magic number is a constant, so neither says anything
// about who sent a packet.  Packets are therefore tagged with a truncated
// HMAC-SHA1 over the packet contents, keyed with a secret that is generated by
// the game host and handed out with the game options when a player joins.

static const Int SHA1_DIGEST_LEN = 20;
static const Int SHA1_BLOCK_LEN = 64;

// Largest region any packet MAC is computed over: the authenticated part of the
// header plus the payload.
static const Int MAX_MAC_INPUT_LEN = MAX_MESSAGE_LEN + sizeof(TransportMessageHeader);

static inline UnsignedInt sha1Rol( UnsignedInt val, Int bits )
{
	return (val << bits) | (val >> (32 - bits));
}

static void sha1ProcessBlock( UnsignedInt *state, const unsigned char *block )
{
	UnsignedInt w[80];
	Int i;

	for (i = 0; i < 16; ++i)
	{
		w[i] = ((UnsignedInt)block[i*4] << 24) | ((UnsignedInt)block[i*4+1] << 16) |
			((UnsignedInt)block[i*4+2] << 8) | ((UnsignedInt)block[i*4+3]);
	}
	for (i = 16; i < 80; ++i)
	{
		w[i] = sha1Rol(w[i-3] ^ w[i-8] ^ w[i-14] ^ w[i-16], 1);
	}

	UnsignedInt a = state[0], b = state[1], c = state[2], d = state[3], e = state[4];
	for (i = 0; i < 80; ++i)
	{
		UnsignedInt f, k;
		if (i < 20)
		{
			f = (b & c) | ((~b) & d);
			k = 0x5A827999;
		}
		else if (i < 40)
		{
			f = b ^ c ^ d;
			k = 0x6ED9EBA1;
		}
		else if (i < 60)
		{
			f = (b & c) | (b & d) | (c & d);
			k = 0x8F1BBCDC;
		}
		else
		{
			f = b ^ c ^ d;
			k = 0xCA62C1D6;
		}

		UnsignedInt temp = sha1Rol(a, 5) + f + e + k + w[i];
		e = d;
		d = c;
		c = sha1Rol(b, 30);
		b = a;
		a = temp;
	}

	state[0] += a;
	state[1] += b;
	state[2] += c;
	state[3] += d;
	state[4] += e;
}

static void sha1Hash( const unsigned char *data, Int len, unsigned char *digest )
{
	UnsignedInt state[5];
	state[0] = 0x67452301;
	state[1] = 0xEFCDAB89;
	state[2] = 0x98BADCFE;
	state[3] = 0x10325476;
	state[4] = 0xC3D2E1F0;

	Int i;
	Int wholeBlocks = len / SHA1_BLOCK_LEN;
	for (i = 0; i < wholeBlocks; ++i)
		sha1ProcessBlock(state, data + i * SHA1_BLOCK_LEN);

	unsigned char tail[SHA1_BLOCK_LEN * 2];
	Int used = len - wholeBlocks * SHA1_BLOCK_LEN;
	memcpy(tail, data + wholeBlocks * SHA1_BLOCK_LEN, used);
	tail[used++] = 0x80;
	Int tailLen = (used <= SHA1_BLOCK_LEN - 8) ? SHA1_BLOCK_LEN : SHA1_BLOCK_LEN * 2;
	memset(tail + used, 0, tailLen - used);

	UnsignedInt bitsHi = ((UnsignedInt)len) >> 29;
	UnsignedInt bitsLo = ((UnsignedInt)len) << 3;
	for (i = 0; i < 4; ++i)
	{
		tail[tailLen - 8 + i] = (unsigned char)((bitsHi >> (24 - i*8)) & 0xff);
		tail[tailLen - 4 + i] = (unsigned char)((bitsLo >> (24 - i*8)) & 0xff);
	}

	for (i = 0; i < tailLen; i += SHA1_BLOCK_LEN)
		sha1ProcessBlock(state, tail + i);

	for (i = 0; i < 5; ++i)
	{
		digest[i*4]   = (unsigned char)((state[i] >> 24) & 0xff);
		digest[i*4+1] = (unsigned char)((state[i] >> 16) & 0xff);
		digest[i*4+2] = (unsigned char)((state[i] >> 8) & 0xff);
		digest[i*4+3] = (unsigned char)(state[i] & 0xff);
	}
}

static void hmacSha1( const unsigned char *key, Int keyLen,
	const unsigned char *data, Int dataLen, unsigned char *digest )
{
	unsigned char shortenedKey[SHA1_DIGEST_LEN];
	if (keyLen > SHA1_BLOCK_LEN)
	{
		sha1Hash(key, keyLen, shortenedKey);
		key = shortenedKey;
		keyLen = SHA1_DIGEST_LEN;
	}

	unsigned char innerBuf[SHA1_BLOCK_LEN + MAX_MAC_INPUT_LEN];
	unsigned char outerBuf[SHA1_BLOCK_LEN + SHA1_DIGEST_LEN];
	Int i;

	memset(innerBuf, 0x36, SHA1_BLOCK_LEN);
	memset(outerBuf, 0x5c, SHA1_BLOCK_LEN);
	for (i = 0; i < keyLen; ++i)
	{
		innerBuf[i] = (unsigned char)(innerBuf[i] ^ key[i]);
		outerBuf[i] = (unsigned char)(outerBuf[i] ^ key[i]);
	}

	memcpy(innerBuf + SHA1_BLOCK_LEN, data, dataLen);
	sha1Hash(innerBuf, SHA1_BLOCK_LEN + dataLen, outerBuf + SHA1_BLOCK_LEN);
	sha1Hash(outerBuf, SHA1_BLOCK_LEN + SHA1_DIGEST_LEN, digest);
}

// Constant-time comparison, so that a MAC cannot be recovered a byte at a time.
static Bool macsMatch( const unsigned char *a, const unsigned char *b, Int len )
{
	unsigned char diff = 0;
	for (Int i = 0; i < len; ++i)
		diff = (unsigned char)(diff | (a[i] ^ b[i]));

	return (diff == 0);
}

//--------------------------------------------------------------------------

Transport::Transport(void)
{
	m_winsockInit = false;
	m_udpsock = NULL;
	m_hasSessionKey = false;
	memset(m_sessionKey, 0, sizeof(m_sessionKey));
	m_numAllowedPeers = 0;
	memset(m_allowedPeers, 0, sizeof(m_allowedPeers));
}

void Transport::setSessionKey( const UnsignedByte *key, Int keyLen )
{
	if (!key || keyLen <= 0)
	{
		clearSessionKey();
		return;
	}

	if (keyLen > TRANSPORT_SESSION_KEY_LEN)
		keyLen = TRANSPORT_SESSION_KEY_LEN;

	memset(m_sessionKey, 0, sizeof(m_sessionKey));
	memcpy(m_sessionKey, key, keyLen);
	m_hasSessionKey = true;
}

void Transport::clearSessionKey( void )
{
	memset(m_sessionKey, 0, sizeof(m_sessionKey));
	m_hasSessionKey = false;
}

void Transport::clearAllowedPeers( void )
{
	m_numAllowedPeers = 0;
	memset(m_allowedPeers, 0, sizeof(m_allowedPeers));
}

void Transport::addAllowedPeer( UnsignedInt addr )
{
	if (addr == 0 || m_numAllowedPeers >= MAX_SLOTS)
		return;

	for (Int i = 0; i < m_numAllowedPeers; ++i)
	{
		if (m_allowedPeers[i] == addr)
			return;
	}

	m_allowedPeers[m_numAllowedPeers++] = addr;
}

Bool Transport::isAllowedPeer( UnsignedInt addr ) const
{
	if (m_numAllowedPeers == 0)
		return true;	// no peer set known (lobby/LAN/NAT traffic) - nothing to filter against

	for (Int i = 0; i < m_numAllowedPeers; ++i)
	{
		if (m_allowedPeers[i] == addr)
			return true;
	}

	return false;
}

/**
 * Compute the authentication tag covering the magic number and the payload.
 * With a session key this is a truncated HMAC-SHA1; without one it falls back
 * to the legacy unkeyed CRC, which is a corruption check only.
 */
void Transport::computeMessageMac( const TransportMessage *msg, Int dataLen, UnsignedByte *mac ) const
{
	const unsigned char *macInput = (const unsigned char *)(&(msg->header.magic));
	Int macInputLen = dataLen + sizeof(TransportMessageHeader) - TRANSPORT_MAC_LEN;

	memset(mac, 0, TRANSPORT_MAC_LEN);
	if (macInputLen < 0 || macInputLen > MAX_MAC_INPUT_LEN)
		return;

	if (m_hasSessionKey)
	{
		unsigned char digest[SHA1_DIGEST_LEN];
		hmacSha1(m_sessionKey, TRANSPORT_SESSION_KEY_LEN, macInput, macInputLen, digest);
		memcpy(mac, digest, TRANSPORT_MAC_LEN);
	}
	else
	{
		CRC crc;
		crc.computeCRC((unsigned char *)macInput, macInputLen);
		UnsignedInt val = crc.get();
		memcpy(mac, &val, sizeof(val));
	}
}

Transport::~Transport(void)
{
	reset();
}

Bool Transport::init( AsciiString ip, UnsignedShort port )
{
	return init(ResolveIP(ip), port);
}

Bool Transport::init( UnsignedInt ip, UnsignedShort port )
{
	// ----- Initialize Winsock -----
	if (!m_winsockInit)
	{
		WORD verReq = MAKEWORD(2, 2);
		WSADATA wsadata;

		int err = WSAStartup(verReq, &wsadata);
		if (err != 0) {
			return false;
		}

		if ((LOBYTE(wsadata.wVersion) != 2) || (HIBYTE(wsadata.wVersion) !=2)) {
			WSACleanup();
			return false;
		}
		m_winsockInit = true;
	}

	// ------- Bind our port --------
	if (m_udpsock)
		delete m_udpsock;
	m_udpsock = NEW UDP();
	
	if (!m_udpsock)
		return false;
	
	int retval = -1;
	time_t now = timeGetTime();
	while ((retval != 0) && ((timeGetTime() - now) < 1000)) {
		retval = m_udpsock->Bind(ip, port);
	}

	if (retval != 0) {
		DEBUG_CRASH(("Could not bind to 0x%8.8X:%d\n", ip, port));
		DEBUG_LOG(("Transport::init - Failure to bind socket with error code %x\n", retval));
		delete m_udpsock;
		m_udpsock = NULL;
		return false;
	}

	// ------- Clear buffers --------
	for (int i=0; i<MAX_MESSAGES; ++i)
	{
		m_outBuffer[i].length = 0;
		m_inBuffer[i].length = 0;
#if defined(_DEBUG) || defined(_INTERNAL)
		m_delayedInBuffer[i].message.length = 0;
#endif
	}
	for (i=0; i<MAX_TRANSPORT_STATISTICS_SECONDS; ++i)
	{
		m_incomingBytes[i] = 0;
		m_outgoingBytes[i] = 0;
		m_unknownBytes[i] = 0;
		m_incomingPackets[i] = 0;
		m_outgoingPackets[i] = 0;
		m_unknownPackets[i] = 0;
	}
	m_statisticsSlot = 0;
	m_lastSecond = timeGetTime();

	m_port = port;

#if defined(_DEBUG) || defined(_INTERNAL)
	if (TheGlobalData->m_latencyAverage > 0 || TheGlobalData->m_latencyNoise)
		m_useLatency = true;

	if (TheGlobalData->m_packetLoss)
		m_usePacketLoss = true;
#endif

	return true;
}

void Transport::reset( void )
{
	if (m_udpsock)
	{
		delete m_udpsock;
		m_udpsock = NULL;
	}

	if (m_winsockInit)
	{
		WSACleanup();
		m_winsockInit = false;
	}

	clearSessionKey();
	clearAllowedPeers();
}

Bool Transport::update( void )
{
	Bool retval = TRUE;
	if (doRecv() == FALSE && m_udpsock && m_udpsock->GetStatus() == UDP::ADDRNOTAVAIL)
	{
		retval = FALSE;
	}
	DEBUG_ASSERTLOG(retval, ("WSA error is %s\n", GetWSAErrorString(WSAGetLastError()).str()));
	if (doSend() == FALSE && m_udpsock && m_udpsock->GetStatus() == UDP::ADDRNOTAVAIL)
	{
		retval = FALSE;
	}
	DEBUG_ASSERTLOG(retval, ("WSA error is %s\n", GetWSAErrorString(WSAGetLastError()).str()));
	return retval;
}

Bool Transport::doSend() {
	if (!m_udpsock)
	{
		DEBUG_LOG(("Transport::doSend() - m_udpSock is NULL!\n"));
		return FALSE;
	}

	Bool retval = TRUE;

	// Statistics gathering
	UnsignedInt now = timeGetTime();
	if (m_lastSecond + 1000 < now)
	{
		m_lastSecond = now;
		m_statisticsSlot = (m_statisticsSlot + 1) % MAX_TRANSPORT_STATISTICS_SECONDS;
		m_outgoingPackets[m_statisticsSlot] = 0;
		m_outgoingBytes[m_statisticsSlot] = 0;
		m_incomingPackets[m_statisticsSlot] = 0;
		m_incomingBytes[m_statisticsSlot] = 0;
		m_unknownPackets[m_statisticsSlot] = 0;
		m_unknownBytes[m_statisticsSlot] = 0;
	}

	// Send all messages
	int i;
	for (i=0; i<MAX_MESSAGES; ++i)
	{
		if (m_outBuffer[i].length != 0)
		{
			int bytesSent = 0;
			// Send this message
			if ((bytesSent = m_udpsock->Write((unsigned char *)(&m_outBuffer[i]), m_outBuffer[i].length + sizeof(TransportMessageHeader), m_outBuffer[i].addr, m_outBuffer[i].port)) > 0)
			{
				//DEBUG_LOG(("Sending %d bytes to %d:%d\n", m_outBuffer[i].length + sizeof(TransportMessageHeader), m_outBuffer[i].addr, m_outBuffer[i].port));
				m_outgoingPackets[m_statisticsSlot]++;
				m_outgoingBytes[m_statisticsSlot] += m_outBuffer[i].length + sizeof(TransportMessageHeader);
				m_outBuffer[i].length = 0;  // Remove from queue
//				DEBUG_LOG(("Transport::doSend - sent %d butes to %d.%d.%d.%d:%d\n", bytesSent,
//					(m_outBuffer[i].addr >> 24) & 0xff,
//					(m_outBuffer[i].addr >> 16) & 0xff,
//					(m_outBuffer[i].addr >> 8) & 0xff,
//					m_outBuffer[i].addr & 0xff,
//					m_outBuffer[i].port));
			}
			else
			{
				//DEBUG_LOG(("Could not write to socket!!!  Not discarding message!\n"));
				retval = FALSE;
				//DEBUG_LOG(("Transport::doSend returning FALSE\n"));
			}
		}
	} // for (i=0; i<MAX_MESSAGES; ++i)

#if defined(_DEBUG) || defined(_INTERNAL)
	// Latency simulation - deliver anything we're holding on to that is ready
	if (m_useLatency)
	{
		for (i=0; i<MAX_MESSAGES; ++i)
		{
			if (m_delayedInBuffer[i].message.length != 0 && m_delayedInBuffer[i].deliveryTime <= now)
			{
				for (int j=0; j<MAX_MESSAGES; ++j)
				{
					if (m_inBuffer[j].length == 0)
					{
						// Empty slot; use it
						memcpy(&m_inBuffer[j], &m_delayedInBuffer[i].message, sizeof(TransportMessage));
						m_delayedInBuffer[i].message.length = 0;
						break;
					}
				}
			}
		}
	}
#endif
	return retval;
}

Bool Transport::doRecv() 
{
	if (!m_udpsock)
	{
		DEBUG_LOG(("Transport::doRecv() - m_udpSock is NULL!\n"));
		return FALSE;
	}

	Bool retval = TRUE;

	// Read in anything on our socket
	sockaddr_in from;
#if defined(_DEBUG) || defined(_INTERNAL)
	UnsignedInt now = timeGetTime();
#endif

	TransportMessage incomingMessage;
	unsigned char *buf = (unsigned char *)&incomingMessage;
	int len = MAX_MESSAGE_LEN;
//	DEBUG_LOG(("Transport::doRecv - checking\n"));
	while ( (len=m_udpsock->Read(buf, MAX_MESSAGE_LEN, &from)) > 0 )
	{
#if defined(_DEBUG) || defined(_INTERNAL)
		// Packet loss simulation
		if (m_usePacketLoss)
		{
			if ( TheGlobalData->m_packetLoss >= GameClientRandomValue(0, 100) )
			{
				continue;
			}
		}
#endif

//		DEBUG_LOG(("Transport::doRecv - Got something! len = %d\n", len));
		// Decrypt the packet
//		DEBUG_LOG(("buffer = "));
//		for (Int munkee = 0; munkee < len; ++munkee) {
//			DEBUG_LOG(("%02x", *(buf + munkee)));
//		}
//		DEBUG_LOG(("\n"));
		// Drop datagrams from addresses that aren't part of the game before they
		// are looked at any further.
		if (!isAllowedPeer(ntohl(from.sin_addr.S_un.S_addr)))
		{
			m_unknownPackets[m_statisticsSlot]++;
			m_unknownBytes[m_statisticsSlot] += len;
			continue;
		}

		decryptBuf(buf, len);

		incomingMessage.length = len - sizeof(TransportMessageHeader);

		if (len <= sizeof(TransportMessageHeader) || !isGeneralsPacket( &incomingMessage ))
		{
			m_unknownPackets[m_statisticsSlot]++;
			m_unknownBytes[m_statisticsSlot] += len;
			continue;
		}

		// Something there; stick it somewhere
//		DEBUG_LOG(("Saw %d bytes from %d:%d\n", len, ntohl(from.sin_addr.S_un.S_addr), ntohs(from.sin_port)));
		m_incomingPackets[m_statisticsSlot]++;
		m_incomingBytes[m_statisticsSlot] += len;

		for (int i=0; i<MAX_MESSAGES; ++i)
		{
#if defined(_DEBUG) || defined(_INTERNAL)
			// Latency simulation
			if (m_useLatency)
			{
				if (m_delayedInBuffer[i].message.length == 0)
				{
					// Empty slot; use it
					m_delayedInBuffer[i].deliveryTime =
						now + TheGlobalData->m_latencyAverage +
						(Int)(TheGlobalData->m_latencyAmplitude * sin(now * TheGlobalData->m_latencyPeriod)) +
						GameClientRandomValue(-TheGlobalData->m_latencyNoise, TheGlobalData->m_latencyNoise);
					m_delayedInBuffer[i].message.length = incomingMessage.length;
					m_delayedInBuffer[i].message.addr = ntohl(from.sin_addr.S_un.S_addr);
					m_delayedInBuffer[i].message.port = ntohs(from.sin_port);
					memcpy(&m_delayedInBuffer[i].message, buf, len);
					break;
				}
			}
			else
			{
#endif
				if (m_inBuffer[i].length == 0)
				{
					// Empty slot; use it
					m_inBuffer[i].length = incomingMessage.length;
					m_inBuffer[i].addr = ntohl(from.sin_addr.S_un.S_addr);
					m_inBuffer[i].port = ntohs(from.sin_port);
					memcpy(&m_inBuffer[i], buf, len);
					break;
				}
#if defined(_DEBUG) || defined(_INTERNAL)
			}
#endif
		}
		//DEBUG_ASSERTCRASH(i<MAX_MESSAGES, ("Message lost!"));
	}

	if (len == -1) {
		// there was a socket error trying to perform a read.
		//DEBUG_LOG(("Transport::doRecv returning FALSE\n"));
		retval = FALSE;
	}

	return retval;
}

Bool Transport::queueSend(UnsignedInt addr, UnsignedShort port, const UnsignedByte *buf, Int len /*,
						  NetMessageFlags flags, Int id */)
{
	int i;

	if (len < 1 || len > MAX_PACKET_SIZE)
	{
		return false;
	}

	for (i=0; i<MAX_MESSAGES; ++i)
	{
		if (m_outBuffer[i].length == 0)
		{
			// Insert data here
			m_outBuffer[i].length = len;
			memcpy(m_outBuffer[i].data, buf, len);
			m_outBuffer[i].addr = addr;
			m_outBuffer[i].port = port;
//			m_outBuffer[i].header.flags = flags;
//			m_outBuffer[i].header.id = id;
			m_outBuffer[i].header.magic = GENERALS_MAGIC_NUMBER;

			computeMessageMac( &m_outBuffer[i], m_outBuffer[i].length, m_outBuffer[i].header.mac );

			// Encrypt packet
//			DEBUG_LOG(("buffer: "));
			encryptBuf((unsigned char *)&m_outBuffer[i], len + sizeof(TransportMessageHeader));
//			DEBUG_LOG(("\n"));

			return true;
		}
	}
	return false;
}

Bool Transport::isGeneralsPacket( TransportMessage *msg )
{
	if (!msg)
		return false;

	if (msg->length < 0 || msg->length > MAX_MESSAGE_LEN)
		return false;

	if (msg->header.magic != GENERALS_MAGIC_NUMBER)
		return false;

	UnsignedByte expectedMac[TRANSPORT_MAC_LEN];
	computeMessageMac( msg, msg->length, expectedMac );

	if (!macsMatch( expectedMac, msg->header.mac, TRANSPORT_MAC_LEN ))
		return false;

	return true;
}

// Statistics ---------------------------------------------------
Real Transport::getIncomingBytesPerSecond( void )
{
	Real val = 0.0;
	for (int i=0; i<MAX_TRANSPORT_STATISTICS_SECONDS; ++i)
	{
		if (i != m_statisticsSlot)
			val += m_incomingBytes[i];
	}
	return val / (MAX_TRANSPORT_STATISTICS_SECONDS-1);
}

Real Transport::getIncomingPacketsPerSecond( void )
{
	Real val = 0.0;
	for (int i=0; i<MAX_TRANSPORT_STATISTICS_SECONDS; ++i)
	{
		if (i != m_statisticsSlot)
			val += m_incomingPackets[i];
	}
	return val / (MAX_TRANSPORT_STATISTICS_SECONDS-1);
}

Real Transport::getOutgoingBytesPerSecond( void )
{
	Real val = 0.0;
	for (int i=0; i<MAX_TRANSPORT_STATISTICS_SECONDS; ++i)
	{
		if (i != m_statisticsSlot)
			val += m_outgoingBytes[i];
	}
	return val / (MAX_TRANSPORT_STATISTICS_SECONDS-1);
}

Real Transport::getOutgoingPacketsPerSecond( void )
{
	Real val = 0.0;
	for (int i=0; i<MAX_TRANSPORT_STATISTICS_SECONDS; ++i)
	{
		if (i != m_statisticsSlot)
			val += m_outgoingPackets[i];
	}
	return val / (MAX_TRANSPORT_STATISTICS_SECONDS-1);
}

Real Transport::getUnknownBytesPerSecond( void )
{
	Real val = 0.0;
	for (int i=0; i<MAX_TRANSPORT_STATISTICS_SECONDS; ++i)
	{
		if (i != m_statisticsSlot)
			val += m_unknownBytes[i];
	}
	return val / (MAX_TRANSPORT_STATISTICS_SECONDS-1);
}

Real Transport::getUnknownPacketsPerSecond( void )
{
	Real val = 0.0;
	for (int i=0; i<MAX_TRANSPORT_STATISTICS_SECONDS; ++i)
	{
		if (i != m_statisticsSlot)
			val += m_unknownPackets[i];
	}
	return val / (MAX_TRANSPORT_STATISTICS_SECONDS-1);
}



